{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cf-monitoring.fullname" . }}-grafana-datasources
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "cf-monitoring.labels" . | nindent 4 }}
    app: grafana
    environment: {{ .Values.global.environment }}
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
    {{- range .Values.grafana.datasources }}
    - name: {{ .name }}
      type: {{ .type }}
      access: {{ .access }}
      url: {{ .url }}
      isDefault: {{ .isDefault }}
      editable: true
      jsonData:
        timeInterval: "30s"
        queryTimeout: "60s"
        httpMethod: "POST"
    {{- end }}
{{- end }}