{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cf-monitoring.fullname" . }}-grafana-admin
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "cf-monitoring.labels" . | nindent 4 }}
    app: grafana
    environment: {{ .Values.global.environment }}
type: Opaque
data:
  admin-user: {{ .Values.grafana.adminUser | b64enc }}
  admin-password: {{ .Values.grafana.adminPassword | b64enc }}
{{- end }}