{{- if and .Values.grafana.enabled .Values.grafana.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cf-monitoring.fullname" . }}-grafana
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "cf-monitoring.labels" . | nindent 4 }}
    app: grafana
    environment: {{ .Values.global.environment }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.grafana.persistence.storageClass }}
  storageClassName: {{ .Values.grafana.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size }}
{{- end }}